# Following Along YouTube Tutorial

### Getting used to PyTorch

In [4]:
# Import 

import torch

In [9]:
# Setting up some tensors.

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

x*y

tensor([10.,  3.])

In [11]:
# Tensor of zeros.

z = torch.zeros([2,5])
z

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [12]:
# THe shape of a tensor. 

z.shape

torch.Size([2, 5])

In [13]:
# Random tensor.

a = torch.rand([2,3])
a

tensor([[0.3163, 0.6846, 0.1253],
        [0.7518, 0.4114, 0.4583]])